project:
  type: website
  output-dir: docs

website:
  title: "Rayan Nasser"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tactical-analysis/index.qmd
        text: Tactical Analysis
      - href: recruitment/index.qmd
        text: Recruitment
      - href: credentials.qmd
        text: Credentials
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/HalfSpacePrince
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/rayan-nasser/
        aria-label: LinkedIn
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto